version: '3'
services:
  web:
    restart: always
    build: ./web
    container_name: dg01
    expose:
      - "8000"
    depends_on:
      - postgres
      - redis
    volumes:
      - django:/usr/src/app
      - static:/www/static
    env_file: .env
    command: /usr/local/bin/gunicorn bamf.wsgi:application -w 2 -b :8000

  nginx:
    restart: always
    build: ./nginx/
    container_name: ng01
    ports:
      - "80:80"
    volumes:
      - static:/www/static
      - django:/usr/src/app
    depends_on:
      - web

  postgres:
    restart: always
    image: postgres:latest
    container_name: ps01
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data/

  redis:
    restart: always
    image: redis:latest
    container_name: rd01
    ports:
      - "6379:6379"
    volumes:
      - redisdata:/data

volumes:
  django:
  static:
  pgdata:
  redisdata:
